### ISSUE TITLE
Readthedocs build failure

### ISSUE THREAD

**Issue by fengsp** [guyskk/flask-restaction#1]
It seems `bson` is missing in you `setup.py` file.

**Comment by guyskk** [comment]
I add `bson` just now, it still failure~~

**Comment by guyskk** [comment]
而且是`validater`依赖`bson`,  https://github.com/guyskk/validater/blob/master/setup.py
这个项目依赖`validater`

**Comment by fengsp** [comment]
The same error ouput?

**Comment by guyskk** [comment]
yes

**Comment by fengsp** [comment]
Do you use `virtualenv` in readthedocs?

**Comment by guyskk** [comment]
I used

**Comment by fengsp** [comment]
https://readthedocs.org/projects/flask-restaction/builds/ All passing...

**Comment by guyskk** [comment]
python /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/bin/sphinx-build

**Comment by guyskk** [comment]
http://flask-restaction.readthedocs.org/zh/latest/api.html 这里无法正常显示API
https://readthedocs.org/projects/flask-restaction/builds/3324170/ 第五项报错

**Comment by fengsp** [comment]
`from bson.objectid import ObjectId`, it seems bson doesn't have any module named `objectid`.

**Comment by fengsp** [comment]
Ok, your `validater` library can't be installed at all, something wrong with your own dev environment.

**Comment by guyskk** [comment]
Are you sure?

You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): bson==0.4.1 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pyjwt==1.4 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): validater==0.6.3 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from Flask==0.10.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from Flask==0.10.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from Flask==0.10.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from bson==0.4.1->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pytz>=2010b in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from bson==0.4.1->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.4 in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from validater==0.6.3->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/docs/checkouts/readthedocs.org/user_builds/flask-restaction/envs/latest/lib/python2.7/site-packages (from Jinja2>=2.4->Flask==0.10.1->-r requirements.txt (line 1))

**Comment by fengsp** [comment]
Sorry, typo, updated.

**Comment by fengsp** [comment]
Your `validater` library can't be imported.

**Comment by guyskk** [comment]
I create virtualenv and build docs on it, it failure, and
```
>>> from bson.objectid import ObjectId
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named objectid
>>>
```

**Comment by fengsp** [comment]
You can not  import something that doesn't exist at all.

**Comment by guyskk** [comment]
Yeah, I find the reason! It seems `bson.objectid.ObjectId` is from `pymongo`, I install pymongo then 
`from bson.objectid import ObjectId` works
