### ISSUE TITLE
flask_sqlalchemy如何结合使用

### ISSUE THREAD

**Issue by adousen** [guyskk/flask-restaction#14]
与flask_sqlalchemy如何结合使用，比如 flask_restful有 marshal方法
另外，scheme如何用，能否给出完整的例子，文档说的不清楚

**Comment by guyskk** [comment]
在$output中声明输出JSON的结构(schema)，框架就能把你返回的对象序列化成JSON数据。
可以返回任意类型的对象，也可以是列表，字典里面嵌套任意类型对象。
把文档 http://restaction-zh-cn.readthedocs.io/quickstart/ 中的 Welcome类 看作 flask_sqlalchemy 的模型类就能理解了。

**Comment by guyskk** [comment]
schema用法的话，可以参考一下 https://github.com/guyskk/purepage/blob/master/api/purepage/views/article.py

**Comment by adousen** [comment]
@guyskk 嗯，明白了，$output声明返回JSON结构，
那何时又在类中定义定义scheme_inputs, scheme_outputs呢，好像这种类还要继承自Resource，这个在文档中好像没有介绍
https://github.com/guyskk/purepage/blob/master/api/purepage/views/comment.py

**Comment by guyskk** [comment]
@adousen 抱歉抱歉，comment.py是旧版本(半年以前)的代码，已经废弃了，这个模块实际也没有用到，本该删掉了。admin.py article.py user.py是新的可以参考。

**Comment by guyskk** [comment]
现在不需要继承Resource类，也不需要定义schema_inputs这些。

**Comment by guyskk** [comment]
另外，https://github.com/guyskk/purepage/tree/master/api/tests 这里是单元测试的写法，用res.py做单元测试会很方便，我写的项目都会做比较完善的单元测试。purepage是一个未完成的项目，因为不明确自己想做什么，所以就暂停了。
