### ISSUE TITLE
关于生成res.js和api文档

### ISSUE THREAD

**Issue by adousen** [guyskk/flask-restaction#15]
使用文档介绍的方法，在控制执行resjs http://127.0.0.1:5000/user -d staric/res.js 命令，错误是id是必须的。因为请求内部错误，可以理解

执行resjs http://127.0.0.1:5000/user?id=1 -d staric/res.js 命令，程序也发生错误，大概因为无法从json中提取meta信息。

不知道是哪里出错？

另外，在config中设置api 路径前缀 不起作用。

**Comment by adousen** [comment]
另外，api文档如何生成？不清楚

**Comment by guyskk** [comment]
API文档(api.meta_view)也是Flask视图，它可以返回HTML或者JSON内容(取决于Accept请求头)
用法在 快速上手 - Welcome 部分:
```
# 配置API文档的访问路径
app.route('/')(api.meta_view)
```

生成res.js
```
resjs http://127.0.0.1:5000 -d staric/res.js
```
这个URL `http://127.0.0.1:5000` 就是文档的URL

**Comment by adousen** [comment]
@guyskk 嗯，解决了。还有一个问题，在config中设置api 路径前缀不起作用，比如：
  app.config["API_URL_PREFIX"] = "/api/v2"

api.add_resource(User) 时，能否像flask_restful那样，指定URL和endpoint参数，我看代码中好像只是简单的以类名的小写附加在app的根路径之下。
```python
 for action_name in actions:
            if action_name == "":
                url = "/" + name
                endpoint = name
            else:
                url = "/{0}/{1}".format(name, action_name)
                endpoint = "{0}@{1}".format(name, action_name)
            action_group = actions[action_name]
            self.app.add_url_rule(
                url, endpoint=endpoint,
                view_func=self.make_view(action_group),
                methods=set(action_group)
            )
```
 最好还能在文档中查到每一个action的URI。

**Comment by guyskk** [comment]
1. `API_URL_PREFIX`这个是给生成res.js用的，做不到用来改变URL前缀。这个名称有些误解，我下一版在文档中注明一下。
2. add_resource指定URL和endpoint参数这个不打算支持，Resource和URL一一对应代码会清晰很多。
如果必须这样做也可以参考这个 https://github.com/guyskk/flask-restaction/issues/8 。
3. 下一版本加上。

**Comment by guyskk** [comment]
补充一下，  
API通常会用Nginx代理到不同目录下，比如`/api/v2`，但是在API内部根目录就是`/`，不关注具体部署在哪，但是生成文档和SDK需要知道部署在哪，所以有`API_URL_PREFIX`这个参数。

add_resource我通常是这样用:
```
ALL_RESOURCE = [getattr(views, x) for x in dir(views) if x[:1].isupper()]
for x in ALL_RESOURCE:
        api.add_resource(x)
```
URL规则就按约定来，这样可以避免flask-restful里面长长的配置列表。

**Comment by guyskk** [comment]
@adousen 已发布新版本
