### ISSUE TITLE
string length must <= 1048576 ?

### ISSUE THREAD

**Issue by crazcdll** [guyskk/flask-restaction#17]
你好，麻烦问一下，我用 `flask-restaction` 创建了一个 `post` API，需要上传一个文件。

我把这个文件转成了二进制数据流，存到了一个 `string` 里面，在发送请求的时候，报错：

`{"error": "InvalidData", "message": "string length must <= 1048576 in upload_files", "status": 400}`

```
def post(self, xxx, xxx, upload_files):
```

请问这个是 `flask-restaction` 有限制吗？

谢谢！

**Comment by guyskk** [comment]
因为 str validator 的默认最大长度（maxlen）是1024*1024，可以设置一个更大的值：
https://github.com/guyskk/validr/blob/master/Isomorph-JSON-Schema.md#built-in-validator

**Comment by crazcdll** [comment]
谢谢，我现在知道是哪里出问题了。

不过，不太清楚要在哪里修改。

我的理解是：既然是 `validr` 这个校验包校验设置的问题，然后它是 `flask-restaction` 自动引入的，那就是要传递一个参数过去，重写这个校验。

不过我不知道该怎么传过去。。

可以再指导一下吗？

谢谢！

**Comment by crazcdll** [comment]
比如：
1. 我如果要添加自己的校验的话，需要导入 `validr` 这个包吗？

2. 我按照下面这个做可以吗？
```
# api.py 启动文件

from flask_restaction import Api, TokenAuth

# 我在这里定义自己的 validators，然后下面引用

api = Api(app, validators=validators, metafile=meta_file)


```


谢谢！

**Comment by guyskk** [comment]
设置字符串长度的问题，在文档字符串的 $input 里写：
```
upload_files?str&maxlen=1000000： upload files
```
`?`后面写参数，和URL查询参数格式差不多。

如果要添加校验器，是按下面那样做（现在这个问题不需要用到自定义校验器）。

**Comment by crazcdll** [comment]
按照你说的，在 $input 里面写了条件，搞定了，谢谢！ @guyskk
