### ISSUE TITLE
Validr已更新至v1.x版本，不再兼容当前版本flask-restaction

### ISSUE THREAD

**Issue by iceihehe** [guyskk/flask-restaction#18]
不维护了吗，我觉得挺好用的。
之所以用1.x的validr，是因为有下面这个BUG
```python
class Demo:
    def get(self, a):
    """
    $input:
        a:
            - int
    """
    pass
```
我想要get方法接收一个参数a，他是个整数列表，但是只能取到第一个
?a=2&a=3&a=5
但是拿到的a是[2]

**Comment by guyskk** [comment]
这个问题 validr 1.x 也不能解决，因为数据是从 request.args 来的，它是 MultiDict 类型，`__getitem__` 方法只返回第一个值。建议用POST方法+JSON传参数。

这个项目我不再继续开发，但如果有PR/Issue我会尽量处理。

**Comment by fatetwist** [comment]
celery_1  |   File "/usr/local/lib/python3.7/site-packages/flask_restaction/api.py", line 15, in <module>
celery_1  |     from validr import Invalid, SchemaParser
celery_1  | ImportError: cannot import name 'SchemaParser' from 'validr' (/usr/local/lib/python3.7/site-packages/validr/__init__.py)

validr版本升级后flask_restaction报错，希望尽快解决

**Comment by iceihehe** [comment]
@guyskk 嗯嗯。有点可惜，还是谢谢了。
