### ISSUE TITLE
开始准备在内部的一个小项目上使用这个库 :P

### ISSUE THREAD

**Issue by Feiox** [guyskk/flask-restaction#3]
我可能在一些我觉得不太好、不太方便、或者有悖 Pythonic 的地方直言不讳的提建议 ~ 希望作者不要太介意 ~ :smile:

**Comment by guyskk** [comment]
不介意的，欢迎提意见

**Comment by guyskk** [comment]
@Feiox 我在内部项目使用这个框架，已经内测一段时间了，不知你的情况怎么样了
